package Chapter08;

public class ExceptionTest4 {


		public static void main(String[] args) {
			
			try {
				int number1 = Integer.parseInt(args[0]);
				int number2 = Integer.parseInt(args[1]);
				
				System.out.println("나누기 결과 : " + (number1 / number2));
				
			} catch (ArrayIndexOutOfBoundsException e) {

				System.out.println("반드시 두 개의 정수를 입력하셔야 합니다.");
			}
			 catch (NumberFormatException e) {

					System.out.println("두 개의 정수를 숫자 형식이어야 합니다.");
				}
			catch (Exception e) {
					//예외처리해줄것이 너무 많을 때 퉁치기용.하지만 사용자 입장을 생각해서 친절한 안내를 위해 안쓰는것을  원칙으로함
				System.out.println("원인 미상의 문제 발생.");
			}
			
			finally {
				System.out.println("예외 발생 여부와 무관하게 무조건 실행되는 영역");
				
			}
			
		}

}
